### ISSUE TITLE
java.lang.NoSuchMethodError: com.intellij.lang.annotation.AnnotationHolder.createAnnotation

### ISSUE THREAD

**Issue by CyberLine** [sonar-intellij-plugin/sonar-intellij-plugin#105]
I use this Plugin with PHPStorm 7.1 and when i Download the Issues, i got the following Error:
(Isses are Downloaded and shown in Inspection window, but not in the files.)
```
com.intellij.lang.annotation.AnnotationHolder.createAnnotation(Lcom/intellij/lang/annotation/HighlightSeverity;Lcom/intellij/openapi/util/TextRange;Ljava/lang/String;)Lcom/intellij/lang/annotation/Annotation;: com.intellij.lang.annotation.AnnotationHolder.createAnnotation(Lcom/intellij/lang/annotation/HighlightSeverity;Lcom/intellij/openapi/util/TextRange;Ljava/lang/String;)Lcom/intellij/lang/annotation/Annotation;
java.lang.NoSuchMethodError: com.intellij.lang.annotation.AnnotationHolder.createAnnotation(Lcom/intellij/lang/annotation/HighlightSeverity;Lcom/intellij/openapi/util/TextRange;Ljava/lang/String;)Lcom/intellij/lang/annotation/Annotation;
	at org.intellij.sonar.analysis.SonarExternalAnnotator.createAnnotation(SonarExternalAnnotator.java:184)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.createAnnotation(SonarExternalAnnotator.java:153)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.createAnnotations(SonarExternalAnnotator.java:99)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.access$100(SonarExternalAnnotator.java:41)
	at org.intellij.sonar.analysis.SonarExternalAnnotator$1.run(SonarExternalAnnotator.java:68)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by omayevskiy** [comment]
do you have the same issue with phpstorm 8?

**Comment by omayevskiy** [comment]
according to jetbrains if plugin works for pycharm CE it should then work for phpstorm. Well it works for pycharm 3 & 4. :-(

**Comment by CyberLine** [comment]
Seems OK for PHPStorm 8.0.2

**Comment by omayevskiy** [comment]
other plugins had the same issue with phpstorm: https://github.com/idok/scss-lint-plugin/issues/5
please try if https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/releases/tag/SNAPSHOT
fixes the issue

**Comment by CyberLine** [comment]
Yes, that works with 7.1 and Annotations are now shown. Thx.
