### ISSUE TITLE
Simplify Local Analysis setup

### ISSUE THREAD

**Issue by tpischke** [sonar-intellij-plugin/sonar-intellij-plugin#112]
As I understand it, in order to run a local analysis, one must first install sonar-runner locally, and then configure the sonar-plugin to call it locally.

This is quite complicated to setup for an entire team, since each team member must perform a number of manual steps before it will work.  The eclipse plugin solves this elegantly by automatically downloading and caching the sonar-runner within the plugin.  This makes configuration of the local analysis trivial and less error-prone.

I would love to see this implemented in this plugin.  Or maybe it already is, and I'm misunderstanding something?

**Comment by omayevskiy** [comment]
it depends on your project, if you use maven, gradle or other build tool for your project, sonar plugin will be already available there, and this is something you need to install anyways.

In general you need some "script" which runs a "prozess" which generats somehow the sonar-report.json. 

I also don't agree that downloding sonar-runner or hard coding a particular version is an elegant solution, as it restricts you from choose which sonar-runner you want to use. It's made for support any kind of project and give the engineer as much freedom as possible.

PS: the sonar eclipse plugin does not work for "non-standard" projects.

**Comment by tpischke** [comment]
We use Maven, but sonar plugin is not available there, as we provide that functionality via a jenkins plugin.  Thus each developer has to manually install sonar in order to be able to run the script.  The eclipse plugin downloads the necessary executables from the sonar server, which I find to be a very elegant solution.

**Comment by omayevskiy** [comment]
> We use Maven, but sonar plugin is not available there, as we provide that functionality via a jenkins plugin. 

Change it ;-)

> The eclipse plugin downloads the necessary executables from the sonar server, which I find to be a very elegant solution.

It is not downloading the sonar-runner itself. It is the sonar-runner which is downloading all needed to perform the analysis. From my understanding the eclipse plugin uses a hard coded version of the sonar-runner, not sure which one. Once you can do something like mvn sonar:sonar all jars will be downloaded for you in the same way.

**Comment by tpischke** [comment]
The problem with installing sonar in the build itself is that then our build has to know about the infrastructure details of our sonar server.  i.e. We will have a server URL in our pom.xml.  Is that really your suggested solution?

**Comment by omayevskiy** [comment]
> We will have a server URL in our pom.xml.
It don't have to be like this, you can use mavens settings.xml and put it on your jenkins server.

Please note that all that questions goes beyond the scope of the plugin itself ;-)

**Comment by tpischke** [comment]
All true.  Just seems unfortunate that the eclipse plugin works out of the box, and the intellij plugin requires us to change the way we build our project.  ;)

**Comment by omayevskiy** [comment]
well, use the official sonar intellij plugin if you like it more, it is made in similiar to the sonar eclipse plugin, supporting java and mvn only with a hard coded sonar-runner

**Comment by tpischke** [comment]
We like your plugin better :).  We couldn't get the official one to work at all.  If you're convinced the hard-coded sonar-runner is a bad approach, then we'll consider changing our build.  But that will take a while, since it will need to be discussed and planned by the team.

**Comment by omayevskiy** [comment]
> We couldn't get the official one to work at all

welcome to the club ;-)

> But that will take a while, since it will need to be discussed and planned by the team.

you really don't need to make any big changes, all you need is on devs local machine run something like:

mvn clean install sonar:sonar -DskipTests=true -Djava.awt.headless=true -Dsonar.language=java -Dsonar.analysis.mode=incremental -Dsonar.host.url=http://your.sonar.server

**Comment by tpischke** [comment]
I'll give it a try

**Comment by tpischke** [comment]
I use the following script to run the local analysis from the windows prompt, which works fine.

```
C:\work\apache-maven-3.0.5\bin\mvn clean install sonar:sonar -DskipTests=true -Djava.awt.headless=true -Dsonar.language=java -Dsonar.analysis.mode=incremental -Dsonar.host.url=https://server.com -Dsonar.login=user -Dsonar.password="password"
```
When I paste this into the local analysis script in the intellij plugin i get this exception.  What am I doing wrong?

```java
ERROR 11:06:36.363 > java.io.IOException: Cannot run program "C:\work\apache-maven-3.0.5\bin\mvn" (in directory "C:\src\capitastra-trunk-fresh"): CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.execute(RunLocalAnalysisScriptTask.java:119)
	at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.run(RunLocalAnalysisScriptTask.java:93)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:154)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:348)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:320)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$6.run(GlobalInspectionContextBase.java:291)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:278)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:288)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$4.run(GlobalInspectionContextBase.java:249)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$9.run(ProgressManagerImpl.java:530)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
	at java.lang.ProcessImpl.start(ProcessImpl.java:136)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
	... 25 more

```

**Comment by tpischke** [comment]
aha, ".bat" extenstion must be added.

**Comment by tpischke** [comment]
Ok, got things working.  Found a bug, reported in #114

**Comment by happyviral** [comment]
I tried with maven 3.3.3, it requires ".cmd" extension.

For eample:
C:\work\apache-maven-3.3.3\bin\mvn.cmd clean install sonar:sonar -DskipTests=true -Djava.awt.headless=true -Dsonar.language=java -Dsonar.analysis.mode=incremental -Dsonar.host.url=https://server.com -Dsonar.login=user -Dsonar.password="password"
