### ISSUE TITLE
Timeout when downloading issues

### ISSUE THREAD

**Issue by nestradaOBS** [sonar-intellij-plugin/sonar-intellij-plugin#121]
Hello,

I have a very large and very slow Sonar server and I'm trying to download the rules as per instructed in the user guide. But I'm getting a timeout issue. It seems to default to 10s I believe? I executed the REST request in my browser and it seems to execute under 10s but by very little (~9-11s).

Here is my stacktrace:

	2015-02-24 19:06:25,180 [ 151604]   INFO - ex.GlobalInspectionContextImpl - Code inspection started 
	2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - Fail to request http://vm-sonar.linky.proj.aql.fr:9000/api/issues/search?componentRoots=com.erdf.linky.linkymat:linkymat-parent&pageSize=-1&resolved=false 
	java.lang.IllegalStateException: Fail to request http://vm-sonar.linky.proj.aql.fr:9000/api/issues/search?componentRoots=com.erdf.linky.linkymat:linkymat-parent&pageSize=-1&resolved=false
		at org.sonar.wsclient.internal.HttpRequestFactory.execute(HttpRequestFactory.java:143)
		at org.sonar.wsclient.internal.HttpRequestFactory.get(HttpRequestFactory.java:126)
		at org.sonar.wsclient.issue.internal.DefaultIssueClient.find(DefaultIssueClient.java:49)
		at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:261)
		at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:76)
		at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:145)
		at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:348)
		at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:320)
		at com.intellij.codeInspection.ex.GlobalInspectionContextBase$6.run(GlobalInspectionContextBase.java:291)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:278)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
		at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:288)
		at com.intellij.codeInspection.ex.GlobalInspectionContextBase$4.run(GlobalInspectionContextBase.java:249)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl$9.run(ProgressManagerImpl.java:530)
		at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
		at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.read(SocketInputStream.java:150)
		at java.net.SocketInputStream.read(SocketInputStream.java:121)
		at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
		at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
		at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:703)
		at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1534)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
		at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
		at org.sonar.wsclient.kevinsawicki.HttpRequest.code(HttpRequest.java:1481)
		at org.sonar.wsclient.internal.HttpRequestFactory.isSuccess(HttpRequestFactory.java:148)
		at org.sonar.wsclient.internal.HttpRequestFactory.execute(HttpRequestFactory.java:136)
	... 26 more
	2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - IntelliJ IDEA 14.0.3  Build #IU-139.1117.1 
	2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - JDK: 1.8.0_25 
	2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - VM: Java HotSpot(TM) Server VM 
	2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - Vendor: Oracle Corporation 
	2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - OS: Windows 7 
	2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - Last Action: InspectCode 
	2015-02-24 19:06:37,144 [ 163568]   INFO - ex.GlobalInspectionContextImpl - Code inspection finished 

Any help is appreciated :)

**Comment by omayevskiy** [comment]
{code}
2015-02-24 19:06:25,180 [ 151604]   INFO - ex.GlobalInspectionContextImpl - Code inspection started 
2015-02-24 19:06:37,144 [ 163568]  ERROR - ex.GlobalInspectionContextImpl - Fail to request http://vm-sonar.linky.proj.aql.fr:9000/api/issues/search?componentRoots=com.erdf.linky.linkymat:linkymat-parent&pageSize=-1&resolved=false 
java.lang.IllegalStateException: Fail to request http://vm-sonar.linky.proj.aql.fr:9000/api/issues/search?componentRoots=com.erdf.linky.linkymat:linkymat-parent&pageSize=-1&resolved=false
{code}
looks like it aborts after 12 secs
if I am not totally wrong the built in timeout is set to 30 secs, seems like your server aborted the connection first ;-)

you can
- try it several times until you get an successful response
- upgrade your server
- upgrade sonar version

**Comment by nestradaOBS** [comment]
Well I looked a bit at the source and in SonarServer, line 50, it seems that the read timeout is 10s. And unless I'm missing something, I simply copy pasted the URL into my browser and it did indeed take a while but I got a response (ie. the server did not abort my connection).

Well I look more into it. Thanks. I'm using Sonar 4.5.1 FYI

**Comment by omayevskiy** [comment]
you are write, increased that to 1 min

**Comment by omayevskiy** [comment]
released

**Comment by nestradaOBS** [comment]
`INFO 11:32:23.888 > Downloaded 153 issues in 00:12:130`
Thanks works great!! :)

**Comment by omayevskiy** [comment]
wow that's really slow ;)
