### ISSUE TITLE
Sonar analysis does not run because of a configuration problem with SCM Stats Plugin

### ISSUE THREAD

**Issue by astrekalova** [sonar-intellij-plugin/sonar-intellij-plugin#122]
Hello,
there is a SCM Stats Plugin on our SonarQube Server. It causes a problem when I run the analysis locally in Eclipse and Intellij. The error message is: 
```
Exception in thread "main" org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.impl.BatchLauncherMain.execute(BatchLauncherMain.java:41)
	at org.sonar.runner.impl.BatchLauncherMain.main(BatchLauncherMain.java:59)
Caused by: Access to the secured property 'sonar.scm.user.secured' is not possible in preview mode. The SonarQube plugin which requires this property must be deactivated in preview mode.
```
In Eclipse there is a possibilty to disable the scm plugin by setting sonar.scm-stats.enabled to false in the SonarQube Plugin preferences. I can not find a similar possibilty in the Intellij Sonarqube Plugin. 
Ca you suggest me a way to solve this problem?

Best wishes,
Alexandra

**Comment by omayevskiy** [comment]
Add to your script a param like -Dsonar.scm-stats.enabled=false ?

**Comment by astrekalova** [comment]
Can you please write me where exactly I should add this parameter - when starting intellij or can I specify it somewhere in the sonarqube options?

**Comment by omayevskiy** [comment]
>when I run the analysis locally 
in the configuration of your local analysis script

**Comment by astrekalova** [comment]
I do not have a local analysis script, I use the intellij plugin for starting the analysis with rules from the remote server. Does the Intellij plugin generate a local script that I can configure?

**Comment by omayevskiy** [comment]
seems like you are using the official sonar plugin. In the community plugin you cannot run local analysis without specifying the local analysis script.

**Comment by astrekalova** [comment]
Yes you are right I used the official plugin. With the community plugin I don't have this problem anymore.
