### ISSUE TITLE
Retrieval of rule description does not authenticate

### ISSUE THREAD

**Issue by dcsobral** [sonar-intellij-plugin/sonar-intellij-plugin#125]
The current use of Retrofit doesn't use the provided authentication values when querying the rule, which can cause an exception due to a 401:

```
401 Unauthorized
retrofit.RetrofitError: 401 Unauthorized
	at retrofit.RetrofitError.httpError(RetrofitError.java:39)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:382)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.intellij.sonar.sonarserver.$Proxy184.show(Unknown Source)
	at org.intellij.sonar.sonarserver.SonarServer.getRule(SonarServer.java:200)
	at org.intellij.sonar.analysis.IssueDescriptionLinkHandler.getDescription(IssueDescriptionLinkHandler.java:79)
	at com.intellij.codeInsight.hint.TooltipLinkHandlerEP.getDescription(TooltipLinkHandlerEP.java:62)
	at com.intellij.codeInsight.daemon.impl.DaemonTooltipRendererProvider$MyRenderer.dressDescription(DaemonTooltipRendererProvider.java:145)
	at com.intellij.codeInsight.hint.LineTooltipRenderer.show(LineTooltipRenderer.java:75)
	at com.intellij.codeInsight.hint.TooltipController.showTooltip(TooltipController.java:139)
	at com.intellij.codeInsight.hint.LineTooltipRenderer.a(LineTooltipRenderer.java:208)
	at com.intellij.codeInsight.hint.LineTooltipRenderer.access$000(LineTooltipRenderer.java:48)
	at com.intellij.codeInsight.hint.LineTooltipRenderer$2.actionPerformed(LineTooltipRenderer.java:126)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by dcsobral** [comment]
I'm finishing a PR for this, using the "get" method available on 4.5.
