### ISSUE TITLE
Failed to download resources from sonarserver (download aborts with 401)

### ISSUE THREAD

**Issue by lkwg82** [sonar-intellij-plugin/sonar-intellij-plugin#127]
I added nemo.sonarsource.org and it failed during download.

Intellij 14.1.2.

```
Cannot fetch SonarQube project and modules from nemo-sonarqube

org.sonar.wsclient.connectors.ConnectionException: HTTP error: 401, msg: Unauthorized, query: org.apache.commons.httpclient.methods.GetMethod@a0f51ea
    at org.sonar.wsclient.connectors.HttpClient3Connector.executeRequest(HttpClient3Connector.java:108)
    at org.sonar.wsclient.connectors.HttpClient3Connector.execute(HttpClient3Connector.java:81)
    at org.sonar.wsclient.Sonar.findAll(Sonar.java:63)
    at org.intellij.sonar.sonarserver.SonarServer.getAllModules(SonarServer.java:244)
    at org.intellij.sonar.sonarserver.SonarServer.getAllProjectsAndModules(SonarServer.java:220)
    at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:110)
    at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:237)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:367)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:623)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by Sinapse87** [comment]
Hi, Are you correctly specifying credentials for your sonar server ?

**Comment by lkwg82** [comment]
I access as anonymous and it starts downloading.

**Comment by aheusingfeld** [comment]
I have exactly the same issue. It seems to me that the plugin is not storing the password. Unfortunately anonymous access to this server is forbidden, so I cannot check that.

IntelliJ: EAP 141.914.3 (JRE_1.8.0_40-internal-b64)
plugin: 2.0.9
Server: SonarQube 5.1 reachable via HTTPS with a self-signed SSL certificate.

**Comment by omayevskiy** [comment]
> I access as anonymous and it starts downloading.

seems like the server does not allow anonymous access.

**Comment by lkwg82** [comment]
It downloads some resources and interrupt with this 401 at some certain point. It seems, theres is a resource, which is not allowed to be accessed.

**Comment by omayevskiy** [comment]
ok, so can we close the issue? ;-)

**Comment by Sinapse87** [comment]
Hi I had the same issue. Can you try to get the same resource simply making a http get ?

**Comment by jfmoy** [comment]
I have the same issue as the one @aheusingfeld mentioned. We have a Sonar instance accessible through HTTPS (self signed certificate), that requires authentication. 

When downloading resources through the SonarQube plugin, I get a HTTP error 401, with message: Unauthorized, query:. I have tried accessing the resources API by hand and it works perfectly when authenticated using my credentials. Any idea or suggestion on how I could debug the issue?

**Comment by rjmadhu** [comment]
Even i am facing the same problem.
NoClassDefFoundError: org/sonar/wsclient/Sonar

Do we have any work around ?

**Comment by tediroca** [comment]
I'm facing the same issue when tryiing to connect through HTTPS and using authentication.

`
Cannot fetch SonarQube project and modules from sonar-server

org.sonar.wsclient.connectors.ConnectionException: HTTP error: 401, msg: Unauthorized, query: org.apache.commons.httpclient.methods.GetMethod@9fd7e2
	at org.sonar.wsclient.connectors.HttpClient3Connector.executeRequest(HttpClient3Connector.java:108)
	at org.sonar.wsclient.connectors.HttpClient3Connector.execute(HttpClient3Connector.java:81)
	at org.sonar.wsclient.Sonar.findAll(Sonar.java:63)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjects(SonarServer.java:167)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjectsAndModules(SonarServer.java:139)
	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:125)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:265)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:569)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by misterfifi1** [comment]
Hi, 

I have exactly the same issue, manually, it works perfectly, it is the same with sonar lint using the token as credential (why this authentication method is not yet accessible?)

Regards,

**Comment by alexandruMihalcea** [comment]
Had the same issue, seems to be due to special characters in the passwords or the password length. Changed password and it worked.

**Comment by poggs** [comment]
I have the same issue which seems to only happen with a 16-character or longer password

**Comment by lkwg82** [comment]
I think this is obsolete now, version of all three parts changed (intellij, plugin and sonarqube).
@poggs I guess you have complete different version setup as I had.

**Comment by coiouhkc** [comment]
Same issue.
IntelliJ Idea Ultimate 2018.2.3
SonarCube 5.3
SonarCube Community Plugin 2.4.0

Trying to access as anonymous, but the plugin tries to access internal `api/components` instead of using `api/project/index` - any chance to correct this behaviour?
