### ISSUE TITLE
Calling invokeAndWait from read-action leads to possible deadlock.

### ISSUE THREAD

**Issue by ktwrenn** [sonar-intellij-plugin/sonar-intellij-plugin#144]
Issue appeared randomly without actually using the plugin. Running IntelliJ 15.0.2
```
Calling invokeAndWait from read-action leads to possible deadlock.
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:721)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.doAnnotate(SonarExternalAnnotator.java:64)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.doAnnotate(SonarExternalAnnotator.java:42)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.f(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.getInfos(ExternalToolPass.java:137)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.runMainPasses(DaemonCodeAnalyzerImpl.java:270)
	at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl$5$1.run(CodeSmellDetectorImpl.java:172)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:123)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:117)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:117)
	at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl$5.run(CodeSmellDetectorImpl.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl.a(CodeSmellDetectorImpl.java:161)
	at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl.access$100(CodeSmellDetectorImpl.java:55)
	at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl$3.run(CodeSmellDetectorImpl.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:626)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by omayevskiy** [comment]
It's a warning Intellij built in with version 15.x. I could not see anything not working because if this, but this definitely needs to be fixed.

**Comment by bdbogjoe** [comment]
same issue for me

**Comment by bentolor** [comment]
This warning annoys me as users repeating on various, semi-random occasions (i.e. on comitting code). Already thinking about disabling the plugin for the mean-time.

**Comment by omayevskiy** [comment]
most annoying is it's not reproducible in debug mode.

**Comment by bentolor** [comment]
Hmmm... seems to be a timing/concurrency issue then? The check itself seems to be present since ever in [ApplicationImpl](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/openapi/application/impl/ApplicationImpl.java).

But the check has a point: According to the stack trace the method _is_ called from within a read action:
````
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:721)
    at org.intellij.sonar.analysis.SonarExternalAnnotator.doAnnotate(SonarExternalAnnotator.java:64)
..
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
````

**Comment by omayevskiy** [comment]
I created a snapshot version: https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/releases/tag/2.0.12-SNAPSHOT

Testing if that helps with the issue is highly welcome :)

**Comment by bentolor** [comment]
Thank you!

I tested it and though I did not see any new warning messages, but I did get a livelock situation. On trying to commit a specific set changes files with the IDEA commit option _"Perform code analysis"_ enabled the IDEA UI freezes at the "Performing code analysis" window.

Please find attach a `jstack` output at this time. Disabling the plugin mended the situtation.

[livelock.txt](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/files/77080/livelock.txt)

**Comment by omayevskiy** [comment]
not good

**Comment by omayevskiy** [comment]
created new snapshot, at least on my machine seems to be resolved now, please verify.

**Comment by bentolor** [comment]
Thank you. Running since yesterday here without any issues!

**Comment by bdbogjoe** [comment]
Good, waiting for release 😃

**Comment by omayevskiy** [comment]
release is out

**Comment by bdbogjoe** [comment]
works fine now, thanks
