### ISSUE TITLE
NullPointerException when start analysis

### ISSUE THREAD

**Issue by rufuslynx** [sonar-intellij-plugin/sonar-intellij-plugin#151]
2016-01-20 16:44:06,021 [2754137]  ERROR - ex.GlobalInspectionContextImpl - IntelliJ IDEA 13.1.6  Build #IU-135.1306
2016-01-20 16:44:06,021 [2754137]  ERROR - ex.GlobalInspectionContextImpl - JDK: 1.7.0_25
2016-01-20 16:44:06,022 [2754138]  ERROR - ex.GlobalInspectionContextImpl - VM: Java HotSpot(TM) 64-Bit Server VM
2016-01-20 16:44:06,022 [2754138]  ERROR - ex.GlobalInspectionContextImpl - Vendor: Oracle Corporation
2016-01-20 16:44:06,022 [2754138]  ERROR - ex.GlobalInspectionContextImpl - OS: Linux
2016-01-20 16:44:06,022 [2754138]  ERROR - ex.GlobalInspectionContextImpl - Last Action: InspectCode
2016-01-20 16:44:06,044 [2754160]   INFO - ex.GlobalInspectionContextImpl - Code inspection finished
2016-01-20 16:53:46,042 [3334158]   INFO - ex.GlobalInspectionContextImpl - Code inspection started
2016-01-20 16:53:48,564 [3336680]  ERROR - ex.GlobalInspectionContextImpl - null
java.lang.NullPointerException
        at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:263)
        at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:76)
        at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:145)
        at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:345)
        at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:317)
        at com.intellij.codeInspection.ex.GlobalInspectionContextBase$6.run(GlobalInspectionContextBase.java:288)
        at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
        at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:285)
        at com.intellij.codeInspection.ex.GlobalInspectionContextBase$4.run(GlobalInspectionContextBase.java:246)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
        at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:380)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
        at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

**Comment by omayevskiy** [comment]
plugin version?
how to reproduce?

**Comment by rufuslynx** [comment]
plugin version - 2.0.9
Reproduce: 
1. Idea Menu -> Analyze -> Inspect Code
2. In Event Log view message now: "NullPointerException: null"

**Comment by omayevskiy** [comment]
current version is 2.0.12 please upgrade

**Comment by rufuslynx** [comment]
all works, thanks
