### ISSUE TITLE
SonarQube (new issues) completes but it does not generate sonar-report.json report

### ISSUE THREAD

**Issue by JimmyRojas** [sonar-intellij-plugin/sonar-intellij-plugin#153]
```java
INFO 15:08:06.004 > INFO: EXECUTION SUCCESS
INFO 15:08:06.004 > INFO: ------------------------------------------------------------------------
INFO 15:08:06.004 > INFO: Total time: 27.100s
INFO 15:08:06.170 > INFO: Final Memory: 70M/1400M
INFO 15:08:06.170 > INFO: ------------------------------------------------------------------------
INFO 15:08:06.652 > finished with exit code 0 in 00:27:808
INFO 15:08:06.652 > Reading issues from /media/HD/jimmy_rojas/AndroidStudioProjects/sonar-report.json
INFO 15:08:06.653 > java.io.FileNotFoundException: /media/HD/jimmy_rojas/AndroidStudioProjects/sonar-report.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
```

**Comment by JimmyRojas** [comment]
It would be my sonar-project.properties

```java
# Required metadata
sonar.projectKey=projectKey
sonar.projectName=projectName
sonar.projectVersion=1.1
sonar.projectDescription=projectDescription

sonar.profile=Android Lint

sonar.language=java
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java

sonar.binaries=app/build/intermediates/classes
sonar.java.binaries=app/build/intermediates/classes

sonar.junit.reportsPath=app/build/test-results

sonar.android.lint.report=app/build/lint-results.xml

sonar.issuesReport.html.enable=true
sonar.issuesReport.json.enable=true
sonar.report.export.path=sonar-report.json
sonar.issuesReport.console.enable=true
```

**Comment by omayevskiy** [comment]
INFO 15:08:06.652 > Reading issues from /media/HD/jimmy_rojas/AndroidStudioProjects/sonar-report.json
INFO 15:08:06.653 > java.io.FileNotFoundException: /media/HD/jimmy_rojas/AndroidStudioProjects/sonar-report.json (No such file or directory)


does this file exists? looking at the path I would say the /target or /build is missing here

**Comment by JimmyRojas** [comment]
thank you for your answer, as you can see, my especification is ignored

sonar.report.export.path=sonar-report.json

**Comment by omayevskiy** [comment]
seems to be correct, it's relative to build root directory

**Comment by JimmyRojas** [comment]
build folder of project/module ?

in my module I have
app/build/sonar/
- report-task.txt

in project I have
/.sonar/
- report-task.txt

but not the xml report file

**Comment by omayevskiy** [comment]
you need to find the path to sonar-report.json in your project

**Comment by JimmyRojas** [comment]
Is this "sonar-report.json" file created temporally ?

**Comment by omayevskiy** [comment]
yes it's created on every build

**Comment by JimmyRojas** [comment]
after run the inspection "SonarQube (new issues)" I can't find any file with that name

**Comment by JimmyRojas** [comment]
Is this "sonar-report.json" file created temporally ?

 @omayevskiy
yes it's created on every build

Is the file kept ? I mean it is created but not deleted?

**Comment by omayevskiy** [comment]
please read the readme first, you need to configure your build in a way it produces that file

**Comment by JimmyRojas** [comment]
hello, I could fix my problem

the issue was in my sonar-project.properties config file

```java
# Required metadata
sonar.projectKey=projectKey
sonar.projectName=projectName
sonar.projectVersion=1.1
sonar.projectDescription=projectDescription

#sonar.profile=Android Lint

sonar.language=java
sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.binaries=build/intermediates/classes
sonar.java.binaries=build/intermediates/classes

sonar.junit.reportsPath=build/test-results

sonar.android.lint.report=build/lint-results.xml

sonar.issuesReport.html.enable=true
sonar.issuesReport.json.enable=true
sonar.report.export.path=sonar-report.json
sonar.issuesReport.console.enable=true
sonar.modules=app
sonar.analysis.mode=preview
#sonar.analysis.mode=issues
```

As you can see I had to remove some properties; those don't work:

sonar.profile=Android Lint
sonar.analysis.mode=publish

**Comment by JimmyRojas** [comment]
using the

sonar.profile=Android Lint

the console displays this:

```java
INFO 18:22:17.083 > INFO: 223 files indexed
INFO 18:22:17.107 > INFO: Quality profile for java: Sonar way
INFO 18:22:17.111 > INFO: ------------------------------------------------------------------------
INFO 18:22:17.111 > INFO: EXECUTION FAILURE
INFO 18:22:17.111 > INFO: ------------------------------------------------------------------------
INFO 18:22:17.111 > INFO: Total time: 2.963s
INFO 18:22:17.209 > INFO: Final Memory: 45M/293M
INFO 18:22:17.209 > INFO: ------------------------------------------------------------------------
ERROR 18:22:17.209 > ERROR: Error during SonarQube Scanner execution
ERROR 18:22:17.209 > ERROR: sonar.profile was set to 'Android Lint' but didn't match any profile for any language. Please check your configuration.
```

**Comment by JimmyRojas** [comment]
some idea ? 
in this doc
http://docs.sonarqube.org/display/SONAR/Analysis+Parameters

I can see "sonar.profile
This property is deprecated since SQ 4.5 LTS (see SONAR-5370 - Deprecate usage of "sonar.profile" as an analysis parameter CLOSED ) and should not be used."

How can I set a profile then ?

**Comment by omayevskiy** [comment]
you should set it on the sonar server
