### ISSUE TITLE
Recurring exception: Module contains 2 content roots and this is not supported

### ISSUE THREAD

**Issue by chludwig-haufe** [sonar-intellij-plugin/sonar-intellij-plugin#155]
Hi,

the SonarLint plugin keeps throwing an exception in one of my Gradle projects. I suspect that the exception appeared only since I recently upgraded to IntelliJ 2016.1.2 (from 2015.x), but I can't swear to it.

The error message is `Module Module: 'content-processing_main' contains 2 content roots and this is not supported`, the stacktrace is below.

The mentioned module has indeed an additional source root for generated code (JAXB).  I don't really care whether the SonarLint plugin can also scan the generated code; the errors reported by IntelliJ many times a day are somewhat annoying, though.

Best regards,
Christoph

> Module Module: 'content-processing_main' contains 2 content roots and this is not supported
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at org.sonarlint.intellij.util.SonarLintUtils.getModuleRoot(SonarLintUtils.java:74)
	at org.sonarlint.intellij.util.SonarLintUtils.shouldAnalyze(SonarLintUtils.java:203)
	at org.sonarlint.intellij.util.SonarLintUtils.shouldAnalyzeAutomatically(SonarLintUtils.java:137)
	at org.sonarlint.intellij.trigger.FileEditorTrigger.fileOpened(FileEditorTrigger.java:67)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:359)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:345)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:338)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy90.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14$1.run(FileEditorManagerImpl.java:974)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$16$1.run(FileEditorManagerImpl.java:1072)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:672)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.i(FocusManagerImpl.java:656)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.c(FocusManagerImpl.java:626)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
	at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by omayevskiy** [comment]
please post sonarlint issues to sonarlint guys,this here is community plugin not related to sonarlint
