### ISSUE TITLE
NoSuchFieldError: PROXY_LOGIN when trying to log into remote server with proxy

### ISSUE THREAD

**Issue by murlinw** [sonar-intellij-plugin/sonar-intellij-plugin#158]
I am having this issue when trying to connect with sonarqube on the remote server through a proxy. I saw  https://intellij-support.jetbrains.com/hc/en-us/community/posts/207729605-NoSuchFieldError-PROXY-LOGIN-on-2016-2-when-trying-to-add-remote-server-to-SonarQube on intellij's forums and he said that this needs to be updated for the newest Intellij. 

Here are the details.

`PROXY_LOGIN
java.lang.NoSuchFieldError: PROXY_LOGIN
	at org.intellij.sonar.sonarserver.SonarServer.createSonarClient(SonarServer.java:68)
	at org.intellij.sonar.sonarserver.SonarServer.<init>(SonarServer.java:48)
	at org.intellij.sonar.sonarserver.SonarServer.create(SonarServer.java:52)
	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:256)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$9.run(CoreProgressManager.java:384)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:555)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by omayevskiy** [comment]
ok this needs to be adjusted to the newest intellij api

**Comment by murlinw** [comment]
Just an FYI, I believe the change is to use `getProxyLogin()` function instead of directly accessing PROXY_LOGIN. 

This is the commit where they changed it. https://github.com/JetBrains/intellij-community/commit/b0375e6db2d63feb1a8ebbad16091454d155bb08

**Comment by omayevskiy** [comment]
thx for the additional infos.

seems to be a minor issue, please verify this version solved it (you will need to manually download the version and install the plugin from your disk):
https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/releases/tag/2.1.0-SNAPSHOT

**Comment by murlinw** [comment]
That appears to have fixed it. Thanks!
