### ISSUE TITLE
Getting NoSuchMethodError after updating to Intellij IDEA 2016.3 and using plugin version 2.1.0

### ISSUE THREAD

**Issue by sherm008** [sonar-intellij-plugin/sonar-intellij-plugin#168]
Here's the stack trace:
com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
java.lang.NoSuchMethodError: com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.isInspectionToolEnabled(SonarQubeInspectionContext.java:86)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:112)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:324)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:392)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:280)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:280)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by initx** [comment]
The same error occur in my phpstorm. Any chances to solve?

**Comment by davidlinse** [comment]
👍

**Comment by kevin-ky** [comment]
I got the same error on Intellij IDEA 2016.3,anyone know how to fix it?

**Comment by omayevskiy** [comment]
looks like they changes the api again

**Comment by omayevskiy** [comment]
please verify if new version solve the issue on your local machine:

https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/releases/tag/2.1.1-SNAPSHOT

**Comment by Kabhal** [comment]
I tested the plugin linked above.
The reported issue seems now ok. However during the Inspection I got a 500 error :
```
Error 500 on http://sonarqube:9000/api/issues/search?componentRoots=com.pkg:Project:master&pageIndex=21&pageSize=-1&resolved=false
org.sonar.wsclient.base.HttpException: Error 500 on http://sonarqube:9000/api/issues/search?componentRoots=com.pkg:Project:master&pageIndex=21&pageSize=-1&resolved=false
	at org.sonar.wsclient.internal.HttpRequestFactory.execute(HttpRequestFactory.java:153)
	at org.sonar.wsclient.internal.HttpRequestFactory.get(HttpRequestFactory.java:129)
	at org.sonar.wsclient.issue.internal.DefaultIssueClient.find(DefaultIssueClient.java:49)
	at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:206)
	at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:82)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:154)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:324)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:392)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:280)
```

I don't know if the problem is related.

Context :
* IDEA 2016.3
* SonarQube 6.0
* The project is a Maven multi-module.
* I launched the inspection on whole project.

**Comment by omayevskiy** [comment]
it's not related, please read the error message from the server...
you have some issues with your sonar server elastic search

**Comment by Kabhal** [comment]
right, all is fine

**Comment by AlexErmer** [comment]
Version 2.1.1-SNAPSHOT works for me!

**Comment by lewisdavidcole** [comment]
Using 2.1.1-SNAPSHOT, I get the same error as Kabhal using IntelliJ IDEA 2016.3.2

> 
Error 500 on http://gthou-apsvn10p:9000/api/issues/search?componentRoots=commercial:Messenger&pageIndex=21&pageSize=-1&resolved=false

**Note that if I remove the `pageSize=-1` from the URL, an error is not thrown and data is returned as expected.**

`
org.sonar.wsclient.base.HttpException: Error 500 on http://gthou-apsvn10p:9000/api/issues/search?componentRoots=commercial:Messenger&pageIndex=21&pageSize=-1&resolved=false
	at org.sonar.wsclient.internal.HttpRequestFactory.execute(HttpRequestFactory.java:153)
	at org.sonar.wsclient.internal.HttpRequestFactory.get(HttpRequestFactory.java:129)
	at org.sonar.wsclient.issue.internal.DefaultIssueClient.find(DefaultIssueClient.java:49)
	at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:206)
	at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:75)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:137)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:324)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:392)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:280)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:280)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by Kabhal** [comment]
@lewisdavidcole This is not related to this issue. You just have too many issues with the rules you configured so that you reach some configured limit in ElasticSearch querying. => Deactivate some rules and correct your code before adding new ones.

**Comment by lewisdavidcole** [comment]
That's one way to look at it. From your response, you are telling us there is a limit to the max issues detected the plugin can handle. There are other options to improve the plugin that could be put into place to eliminate this concern. 1) Expose the index.max_result_window parameter of elastic search through your configuration. 2) As the ElasticSearch error states, alter your implementation to use the recommended scroll api, which can handle large data sets.

**Comment by Kabhal** [comment]
Sure ;) SQ could better manage this point. I was just pointing out our problem is not related to this issue. You could probably open a new enhancement issue.
FYI, I tried but failed to configure the ES's index.max_result_window through SQ.

**Comment by lewisdavidcole** [comment]
You are correct that the index.max_result_window needs to be configured on the SQ side. I tried it also with no luck. I will open an enhancement request with SQ and see if it's possible they can expose the setting. In the meantime, I will reduce the rules and move forward.

**Comment by lewisdavidcole** [comment]
@Kabhal I created an issue with SonarQube: [SONAR-8005](https://jira.sonarsource.com/browse/SONAR-8005?jql=text%20~%20%22index.max_result_window%22
)
The response was: 

> Yes, indeed you cannot return more than the 10'000th issue. With page size put at -1 it takes the maximum size, which is 500 for a page size.
> This WS is NOT meant to return all the issues of a SonarQube instance

So in case it helps anyone else, there is a hard maximum of 10,000 issues within a project before the plugin crashes.

**Comment by solitory-mark** [comment]
I updated the "SonarQube Community Plugin" and problem solved

**Comment by mhermosi** [comment]
2017.2 neither
