### ISSUE TITLE
Problems with pagination

### ISSUE THREAD

**Issue by yrch1** [sonar-intellij-plugin/sonar-intellij-plugin#172]
Hi,

When i try to analyze my project using the pluging, it shows that there are 31 pages, but suddlenly it fails with page 21. With page 20 it works fine

`Error 500 on https://waslp22v01d.dcs.dinersclub.es/sonar/api/issues/search?componentRoots=es.dinersclub:atrium&pageIndex=21&pageSize=-1&resolved=false
org.sonar.wsclient.base.HttpException: Error 500 on https://waslp22v01d.dcs.dinersclub.es/sonar/api/issues/search?componentRoots=es.dinersclub:atrium&pageIndex=21&pageSize=-1&resolved=false
	at org.sonar.wsclient.internal.HttpRequestFactory.execute(HttpRequestFactory.java:153)
	at org.sonar.wsclient.internal.HttpRequestFactory.get(HttpRequestFactory.java:129)
	at org.sonar.wsclient.issue.internal.DefaultIssueClient.find(DefaultIssueClient.java:49)
	at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:206)
	at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:75)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:137)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:324)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:392)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:280)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:280)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by bugatino** [comment]
This issue fixed yet?? I encountered the same error. Of mine, it shows that there are 24 page, but get fail at p=21, with p=20 it working fine.
@yrch1 Are you fixed this error?

**Comment by brunoeustaquio** [comment]
in case someone else faces the same problem, changing `index.max_result_window` to a higher value can help: https://stackoverflow.com/questions/35206409/elasticsearch-2-1-result-window-is-too-large-index-max-result-window/35223055#35223055
