### ISSUE TITLE
Download of resources is failing due to change in sonarqube api

### ISSUE THREAD

**Issue by vsfalexanderpilch** [sonar-intellij-plugin/sonar-intellij-plugin#179]
The download of resources is failing/returning an empty list:
![screen1](https://cloud.githubusercontent.com/assets/15819119/26256040/ec0a41a0-3cbb-11e7-881d-c12d22541268.png)

If the url is changed to some invalid sonar url it's showing this error:
![screen2](https://cloud.githubusercontent.com/assets/15819119/26256061/00ad81c6-3cbc-11e7-887b-6c72efabe765.png)

The plugin seems to be using the /api/resources endpoint of sonarqube, which was removed in 6.3:
![screen3](https://cloud.githubusercontent.com/assets/15819119/26256085/1140a216-3cbc-11e7-9701-b9e396afefc6.png)
See <sonarqube_base_url>/api/webservices/list for a list of services

It seems that the sonar-ws-client needs to be replaced.

This was verified with 2.1.1-SNAPSHOT in IDEA 2017.1.3 (build 171.4424.56) , Sonarqube 6.3.1(build 21392)

**Comment by rezass** [comment]
same problem here

**Comment by marsc** [comment]
@omayevskiy Could you please take a look a this?

**Comment by omayevskiy** [comment]
the plugin does not support different sonarqube versions yet

**Comment by atextor** [comment]
As I understand, although downloading resources does not work, the actual functions of the plug-in still work. So, is there a way to at least manually add resources the get the plug-in to work, e.g., in a config file? The settings dialog doesn't allow me to manually add an entry.

**Comment by Vampire** [comment]
@omayevskiy do you plan to support different versions, or at least make it compatible to the latest API? We just upgraded our SQ instance to 6.5 and cannot properly use the plugin now. :-(

**Comment by angelyangw** [comment]
the same problem

**Comment by omayevskiy** [comment]
@Vampire currently I am not planning to support different versions.

**Comment by Vampire** [comment]
@omayevskiy and how about supporting the latest version?

**Comment by omayevskiy** [comment]
@Vampire the project is open to the community and for pull requests ;)

**Comment by Vampire** [comment]
Sure, but the question is whether you would accept such a PR. You could also say "I need to use an ancient SQ version and need the plugin to work with that", then creating such a PR would be waste of time. :-)

**Comment by Vampire** [comment]
Testers needed.

Fellow waiters, here a version to test: [sonar-intellij-plugin-2.1.3-SNAPSHOT.zip](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/files/1341062/sonar-intellij-plugin-2.1.3-SNAPSHOT.zip)

Please give it a try and let me know if everything works as expected. I needed to change most of the remote stuff, so not only test the resource downloading but everything and let me know if something behaves strange.

I'll open a PR with the code as soon as October has started to get this in for Hacktoberfest. :-)

**Comment by Vampire** [comment]
Actually now that I know from this work that everything besides `key`, `name` and `qualifer` are not used anyway and are just an artefact of using a library obejct as serialized data, I'm happy with the current version anyway, because now I'll just generate the configuration. :-)

**Comment by omayevskiy** [comment]
> Sure, but the question is whether you would accept such a PR
if "it works" I would of course.Beyond this every who wants is welcome to become a "full developer"

**Comment by omayevskiy** [comment]
> I need to use an ancient SQ version and need the plugin to work with that

I personally need it to work with version 5.6.1

**Comment by Vampire** [comment]
@omayevskiy I think it should work with 5.6.x, did you try my provided snapshot version?

**Comment by omayevskiy** [comment]
@Vampire I get an "Plugin is incompatible with this installation error
my idea version: 2017.2.4

**Comment by Vampire** [comment]
@omayevskiy I tested it with 2016.1 with one commit undone that was not compatible with 2016.1 anymore. But the one I provided here was compiled with latest master branch and my changes.

**Comment by omayevskiy** [comment]
Are you sure? I recently uploaded a new version, check if your fork is up-to-date.

**Comment by Vampire** [comment]
it is, I just checked

**Comment by omayevskiy** [comment]
my bad, I did not push latest changes to master, now it's up-to-date

**Comment by Vampire** [comment]
Ok, here an updated version: [sonar-intellij-plugin-2.1.4-SNAPSHOT.zip](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/files/1348693/sonar-intellij-plugin-2.1.4-SNAPSHOT.zip)

**Comment by Vampire** [comment]
And I also created the PR now that october started :-)

**Comment by omayevskiy** [comment]
got this exception
```
Fail to request https://MY_HOST/sonar/api/issues/search?componentRoots=my.org:my-project&ps=-1&resolved=false
java.lang.IllegalStateException: Fail to request https://MY_HOST/sonar/api/issues/search?componentRoots=my.org:my-project&ps=-1&resolved=false
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:176)
	at org.sonarqube.ws.client.HttpConnector.get(HttpConnector.java:112)
	at org.sonarqube.ws.client.HttpConnector.call(HttpConnector.java:99)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:55)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:50)
	at org.sonarqube.ws.client.issue.IssuesService.search(IssuesService.java:161)
	at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:150)
	at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:75)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:137)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:321)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:397)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:279)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:342)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:173)
	... 30 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 57 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 63 more
```

**Comment by Vampire** [comment]
@omayevskiy sounds like your SonarQube instance uses a self-signed certificate, or does not properly send the cerificate chain with the answer. We had this problem with some of our servers and consuming client applications (not only SonarQube) when we switched to the free `Let's Encrypt` certificates and the IT didn't properly configure the server to send the certificate chain. Browsers are pretty lax about this sometimes you could check with `wget` or `curl`. When our servers were not properly configured, it worked in browsers, but failed with the same error you get in those tools.

**Comment by omayevskiy** [comment]
@Vampire yes, the plugin should behave relaxed here as well, with current prod version it does ignore this issue

**Comment by Vampire** [comment]
Well, that is probably open for discussion, it has a reason that those certificates are not trusted by default. But actually I didn't change anything in this regard. I guess the old ws-client accepted them while the new one does not. We only have a properly configured instance here. But hey, you are the maintainer, if you feel the plugin should unconditionally accept potentially insecure certificates, be my guest to change it. :-)

**Comment by Vampire** [comment]
You could try adding

```
.setTrustManager(new X509TrustManager() {
    @Override
    public void checkClientTrusted(X509Certificate[] x509Certificates, String s) throws CertificateException {
    }

    @Override
    public void checkServerTrusted(X509Certificate[] x509Certificates, String s) throws CertificateException {
    }

    @Override
    public X509Certificate[] getAcceptedIssuers() {
        return new X509Certificate[0];
    }
})
```

to the `HttpConnector.Builder` call-chain in `org.intellij.sonar.sonarserver.SonarServer#createSonarClient` line 67 to unconditionally accept all certificates.

But I'd recommend to either add a configuration option that defaults to false, or maybe you can even use `com.intellij.util.net.ssl.ConfirmingTrustManager.createForStorage(...)` to create a trust store that asks the user for insecure certificates. I guess that would be the best choice, but I can not really test it here.

**Comment by Vampire** [comment]
Ok, I remembered that I have Fiddler Proxy on my box which I can set up as Man-In-The-Middle HTTPS proxy which results in all requests delivering a self-signed certifcate, so I was able to test it. Here a version with the confirming trust manager used and working: 
[sonar-intellij-plugin-2.1.4-SNAPSHOT.zip](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/files/1358431/sonar-intellij-plugin-2.1.4-SNAPSHOT.zip)
I also updated PR #186 accordingly.

**Comment by omayevskiy** [comment]
@Vampire

will test it again and give feedback next week.

**Comment by omayevskiy** [comment]
Got no exception, but a pop up window asking me if I want to accept the certificate

**Comment by Vampire** [comment]
Sounds correct, that is exactly what I intended. :-)

**Comment by omayevskiy** [comment]
@Vampire what do you mean?
even after entering credentials, it still does not work to download the resouces. With previous version it works.

**Comment by Vampire** [comment]
I answered before you edited the comment, or at least I didn't see the comment edit when I answered. Are you sure your credentials are correct? For me downloading worked fine.

**Comment by omayevskiy** [comment]
credentials are correct, I am sure, furthermore downloading resources does not require credentials ;-)

**Comment by Vampire** [comment]
Sure it does.
If you request https://your-sonarqube-instance/api/components/search?qualifiers=TRK,BRC  without authentication, you get 401, if you request with authentication it works fine.

**Comment by Vampire** [comment]
Well, it probably depends on how you set up security on the SQ instance

**Comment by omayevskiy** [comment]
well with the older version it did not require authentication, not sure which url it used

**Comment by omayevskiy** [comment]
@Vampire 
indeed, after entering my credentials , that I did not had to add before, downloading resources works now. Furthermore it's now nearly to instantly downloaded compared to previous it took a couple of seconds ;-)

**Comment by Vampire** [comment]
Yes, that is probably because the new ws-client lib does not use JSON anymore, but Google Protocol Buffers which needs waaaay less bandwith and parsing time, that is an additional bonus. :-)
Maybe the old SonarQube WebService provided the list of resources without login.

**Comment by Vampire** [comment]
The old version used another URL that is long deprecated and now removed which is why the downloading did not work anymore at all, which is the cause of this ticket :-)

**Comment by omayevskiy** [comment]
alright, I made my 2 cents comments on the pull request, if you are fine, we can bring this out to other people

**Comment by Vampire** [comment]
I replied and also updated the PR, feel free to review again :-)

**Comment by omayevskiy** [comment]
reviewed again ✔️

**Comment by Vampire** [comment]
new cycle :-D

**Comment by omayevskiy** [comment]
lgtm
if you like you can still do minor changes, otherwise I would release within the next few days

**Comment by Vampire** [comment]
It's ok, I'm all for striving for perfection :-)

**Comment by Poeschl** [comment]
Quick question, is the new version also supporting Version 6.3 of SQ?

**Comment by omayevskiy** [comment]
released release v2.1.4

**Comment by Vampire** [comment]
@Poeschl yes

**Comment by linrongbin16** [comment]
Hi, I meet the `download resources empty` issue, is the newest plugin support SonarQube server Version 5.6.5 ?

My team use SonarQube server Version 5.6.5, version info at bottom of website:
![image](https://user-images.githubusercontent.com/6496887/60145845-eec43e00-97f9-11e9-947a-cb6b8f511ca7.png)

And I use the newest IntelliJ IDEA and newest SonarQube Community Plugin, which download resources are empty.
![image](https://user-images.githubusercontent.com/6496887/60145940-39de5100-97fa-11e9-8276-77cbe735ffdd.png)

Should I use plugin with specified version for this server (I cannot change the server's version since all team use it) ? And which version should I use ?

Thanks!
