### ISSUE TITLE
Cannot fetch SonarQube project and modules

### ISSUE THREAD

**Issue by Poeschl** [sonar-intellij-plugin/sonar-intellij-plugin#187]
Hi there,
I just installed the sonar plugin with brandnew version 2.1.4 in combination with a company-hosted SQ 6.3.
By fetching the existing resources from SQ I get following error dialog.

Any ideas?

```
Cannot fetch SonarQube project and modules from Sonarqube

org.sonarqube.ws.client.HttpException: Error 400 on https://**************/api/components/tree?componentId=72285183-5bb8-446f-9e06-5408c48826f8&qualifiers=BRC : {"errors":[{"msg":"Either 'baseComponentId' or 'baseComponentKey' must be provided, not both"}]}
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:55)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:50)
	at org.sonarqube.ws.client.component.ComponentsService.tree(ComponentsService.java:71)
	at org.intellij.sonar.sonarserver.SonarServer.getAllModules(SonarServer.java:144)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjectsAndModules(SonarServer.java:122)
	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:261)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:590)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by ejgreenwald** [comment]
I have the same issue.
![capture](https://user-images.githubusercontent.com/11929532/31624076-704ac7ae-b26f-11e7-89fc-a0e8a9221269.JPG)

**Comment by omayevskiy** [comment]
you need to provide credentials

**Comment by omayevskiy** [comment]
@Vampire any idea?

**Comment by Vampire** [comment]
The problem is not a missing login, but a version conflict. In version 6.4 of `sonar-ws` the parameter `baseComponentId` was replaced with `componentId`. But 6.3 does not yet support `componentId`. SonarSource recommends to always use the matching `sonar-ws` version to talk to a SonarQube instance, but for this you would either need to have some code that ships all sonar-ws versions and selects the one to use at runtime from the server version or provide different variants of the plugin for different SonarQube server versions. As a quickfix to support non-recent SonarQube versions it might help to use an older `sonar-ws` version and rebuild the plugin, but there might then be other hassles, especially as now there is not JSON used anymore but Protocol Buffers which as far as I remember needs to exactly match, as only the data is transmitted, no structure information like field names.

**Comment by omayevskiy** [comment]
> to have some code that ships all sonar-ws versions

yes this would be multi sonar servers support :)

**Comment by omayevskiy** [comment]
@Vampire I think about something like:
https://stackoverflow.com/a/42981080

and then hav different client implementations depending on the server version

**Comment by Vampire** [comment]
Well, I wouldn't use a text editor, but a proper shading plugin for Gradle if using that strategy.

But I guess I'd personally prefer to use a custom class loader that loads the correct JAR for the respective server version.

**Comment by omayevskiy** [comment]
hm class loader would be tricky we also need different implementations. depending on sonar-ws version you might nneed to implement it little different, thus with the renaming hack you could have all the versions at compile time and implement in normal way different versions.

someting like:
import org.sonarqube.ws.v5
import org.sonarqube.ws.v6

and

public class SonarServerV5
public class SonarServerV6

...

**Comment by Vampire** [comment]
I don't think it will be too complicated. You make one Gradle sub-project per client implementation with the respective sonar-ws version as compileOnly dependency, then all can properly compile independently. And then you can either name them differently and include the implementations in the main class loader, only loading the respective sonar-ws library in the custom class loader or naming the implementations equal and also load them on the custom class loader. The latter might be easier and more elegant.

**Comment by omayevskiy** [comment]
we can try it

**Comment by omayevskiy** [comment]
for a quick solution: upgradinng to SQ v 6.4 helps with the issue

**Comment by Poeschl** [comment]
Not a solution for me, using it in a company and the SQ version is fixed to 6.3 right now.

**Comment by Vampire** [comment]
@Poeschl I already gave you a quick solution. Recompile with ws-client 6.3 and use it, that should do it.

**Comment by Vampire** [comment]
@Poeschl I already gave you a quick solution. Recompile with ws-client 6.3 and use it, that should do it.

**Comment by Poeschl** [comment]
@Vampire I will test it tomorrow, hadn't the time for it the last days 😉
I'm positive that one is working

**Comment by Poeschl** [comment]
With a repro copy and the matching version of SQ 6.3 the plugin is working as expected.
Should this issue should be closed or should it stay as a reminder?

**Comment by Vampire** [comment]
I'd say it should stay. It is the "support multiple SQ versions" issue actually.

**Comment by omayevskiy** [comment]
I'd also say it should stay, we should prove long term support for the different server versions issue

**Comment by Poeschl** [comment]
Leaving it open ...

**Comment by hpdrofus** [comment]
Hi, I am having exactly the same issue.
@Poeschl or @Vampire, can you please help me on what to do in order to match the SonarCube 6.3 version?
I currently have SQ 5.6.7 in the server, and I am using the Sonar Intellij Plugin 2.3.0.
Thank you!

**Comment by Poeschl** [comment]
@hpdrofus 
Steps to success:
* Clone this repository locally
* replace the version `6.5` in [build.gradle: 30](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/blob/master/build.gradle#L30) with `5.6.7`
* build the project with `.\gradlew assemble` from the project root
* Open Intellij Plugin Settings -> `Install plugin from disk` -> select the previous build plugin from your local clone (`/path/to/clone/build/lib/sonar-intellij-plugin.zip`)
* Success
