### ISSUE TITLE
Cannot fetch SonarQube project and modules

### ISSUE THREAD

**Issue by DaRolla** [sonar-intellij-plugin/sonar-intellij-plugin#192]
Hi there,

![grafik](https://user-images.githubusercontent.com/7449372/35146897-d8e2aeac-fd0c-11e7-9b5d-314ff7afc9d1.png)

I am using IntelliJ, and configuring the plugin starts with the "Download resources" button. So using my local docker sonarcube I get this stacktrace.

	org.sonarqube.ws.client.HttpException: Error 401 on http://192.168.99.100:9000/api/components/search?qualifiers=TRK : 
		at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
		at org.sonarqube.ws.client.BaseService.call(BaseService.java:55)
		at org.sonarqube.ws.client.BaseService.call(BaseService.java:50)
		at org.sonarqube.ws.client.component.ComponentsService.search(ComponentsService.java:58)
		at org.intellij.sonar.sonarserver.SonarServer.getAllProjects(SonarServer.java:137)
		at org.intellij.sonar.sonarserver.SonarServer.getAllProjectsAndModules(SonarServer.java:110)
		at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:120)
		at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
		at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
		at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:397)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
		at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:575)
		at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

Opening the same link inside a browser works quite well:

	{
		"paging": {
			"pageIndex": 1, 
			"pageSize": 100, 
			"total": 1
		}, 
		"components": [
			{
				"organization": "default-organization", 
				"id": "AWENm9wGK7hQz7Z5F19z", 
				"key": "Testprojekt_Key:123", 
				"name": "Testprojekt", 
				"qualifier": "TRK"
			}
		]
	}

Greetings,
DaRolla

PS: Docker sonarcube is **Version 6.3.1 (build 21392)**. But another sonarcube with **Version 5.6.6** doesn't work either...

**Comment by anzebra** [comment]
Do you have any updates? I have the same issue

**Comment by akmaharshi** [comment]
I still have the same issue, any updates.
