### ISSUE TITLE
Cannot run SonarQube inspection in IntelliJ 2017.3

### ISSUE THREAD

**Issue by jaspervandaele** [sonar-intellij-plugin/sonar-intellij-plugin#194]
When I try to run the SonarQube Inspection in IntelliJ 2017.3 community, I get this error:
```
Fail to parse protobuf response of http://**********/sonardev/api/issues/search?componentRoots=***.*******:*******&ps=-1&resolved=false
java.lang.IllegalStateException: Fail to parse protobuf response of http://**********/sonardev/api/issues/search?componentRoots=***.*******:*******&ps=-1&resolved=false
	at org.sonarqube.ws.client.BaseService.convert(BaseService.java:64)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:51)
	at org.sonarqube.ws.client.issue.IssuesService.search(IssuesService.java:161)
	at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:154)
	at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:75)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:137)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:317)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:401)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$2(GlobalInspectionContextBase.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:279)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:99)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:530)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:493)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:611)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:281)
	at com.google.protobuf.CodedInputStream.readGroup(CodedInputStream.java:424)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:520)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:493)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:611)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:281)
	at com.google.protobuf.CodedInputStream.readGroup(CodedInputStream.java:424)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:520)
	at com.google.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:276)
	at org.sonarqube.ws.Issues$SearchWsResponse.<init>(Issues.java:260)
	at org.sonarqube.ws.Issues$SearchWsResponse.<init>(Issues.java:221)
	at org.sonarqube.ws.Issues$SearchWsResponse$1.parsePartialFrom(Issues.java:2684)
	at org.sonarqube.ws.Issues$SearchWsResponse$1.parsePartialFrom(Issues.java:2678)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:169)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.sonarqube.ws.client.BaseService.convert(BaseService.java:62)
	... 27 more
```

You need to be authorized to access the URL. I can get a proper JSON response when calling the same URL with a rest client (postman). I get an XML response like this if I try to reach the URL without authorization:

`<error><code>401</code><msg>Unauthorized</msg></error`

This was working just fine before. I'm not sure since what change it stopped working (sonarQube server, the plugin or IntelliJ upgrade)

**Comment by bsmukasa** [comment]
This is also not working for Intellij 2018.1 applications

**Comment by gaggle** [comment]
@omayevskiy would you prefer a separate issue to track for 2018.1 incompatibility? FWIW I am currently on 2017.3.5 (build 173.4674.33) where the plugin works.

**Comment by Gerros** [comment]
@gaggle same for me... with the latest 2017 version it worked, now with 2018 it does not. 
```Java
com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
java.lang.NoSuchMethodError: com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.isInspectionToolEnabled(SonarQubeInspectionContext.java:86)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:112)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:317)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:388)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$2(GlobalInspectionContextBase.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:279)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:234)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Thomas-Schindler** [comment]
> I have:
> SonarQube Version 4.5.4
> sonar-intellij-plugin 2.2.0

@jaspervandaele The latest release I got offered for sonar-intellij-plugin from the Marketplaces is 2.0.12. Was "2.20" a typo or is there a release out which I don't see?
