### ISSUE TITLE
plugin does not work with 2018 version of intellij

### ISSUE THREAD

**Issue by Gerros** [sonar-intellij-plugin/sonar-intellij-plugin#195]
with the latest intellij version 2018.1 the plugin does not work anymore
```Java
com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
java.lang.NoSuchMethodError: com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.isInspectionToolEnabled(SonarQubeInspectionContext.java:86)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:112)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:317)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:388)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$2(GlobalInspectionContextBase.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:279)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:234)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cless00** [comment]
After update to 2018.1 from 2017.3, sonarqube community plugin was downgraded to 2.1 and did not work.

**Comment by globanov** [comment]
Got same issue on PyCharm 2018.1

**Comment by zybreak** [comment]
Created a Pull Request with a possible fix

**Comment by zybreak** [comment]
If you want to try it out, checkout the source build with `gradle buildPlugin` and install the zip file located under `build/distributions` (note build with jdk1.8)

**Comment by Vampire** [comment]
@omayevskiy are you going to fix this? Otherwise you probably get a flood of issues opened as the last version marked compatible is used which is 2.1.0 and indeed is not the least compatible.

**Comment by omayevskiy** [comment]
yes will take care this weekend
