### ISSUE TITLE
https://sonarcloud.io - Cannot fetch SonarQube project and modules from SonarCloud

### ISSUE THREAD

**Issue by jchenry-erudo** [sonar-intellij-plugin/sonar-intellij-plugin#209]
i use (User : token)

Cannot fetch SonarQube project and modules from SonarCloud

org.sonarqube.ws.client.HttpException: Error 401 on https://sonarcloud.io/api/components/search?qualifiers=TRK : 
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:55)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:50)
	at org.sonarqube.ws.client.component.ComponentsService.search(ComponentsService.java:58)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjects(SonarServer.java:137)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjectsAndModules(SonarServer.java:110)
	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:574)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jchenry-erudo** [comment]
![erreur](https://user-images.githubusercontent.com/41893231/45429641-fd46cc00-b6a3-11e8-902d-235d49250339.png)

**Comment by omayevskiy** [comment]
fetching resources from sonarcloud using token works to me
