### ISSUE TITLE
HttpException downloading issues from sonar server

### ISSUE THREAD

**Issue by jwenting** [sonar-intellij-plugin/sonar-intellij-plugin#215]
Sonar version 6.7.5
Sonar plugin version 2.4.1

org.sonarqube.ws.client.HttpException: Error 500 on https://sonar.XXXXXXXX/api/issues/search?componentRoots=XXXXXXXXXXXXXXXXXXXXXXXXX&p=21&ps=-1&resolved=false : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:55)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:50)
	at org.sonarqube.ws.client.issue.IssuesService.search(IssuesService.java:161)
	at org.intellij.sonar.sonarserver.SonarServer.getAllIssuesFor(SonarServer.java:169)
	at org.intellij.sonar.analysis.DownloadIssuesTask.run(DownloadIssuesTask.java:76)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:137)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:317)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:388)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$2(GlobalInspectionContextBase.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:279)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:234)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

It seems the ps=-1 is causing the error. 
This project has a lot of sonar issues, 15000 or so (reworking legacy code...).

**Comment by omayevskiy** [comment]
Error 500 on https://sonar.XXXXXXXX/api/issues/search?componentRoots=XXXXXXXXXXXXXXXXXXXXXXXXX&p=21&ps=-1&resolved=false : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

it's error on server side, check server logs
