### ISSUE TITLE
Unable to download sources

### ISSUE THREAD

**Issue by djas19** [sonar-intellij-plugin/sonar-intellij-plugin#222]
Since merge #218 i'm no longer able to download sources:

`org.sonarqube.ws.client.HttpException: Error 400 on https://our.project.be/api/components/search?qualifiers=TRK&ps=10000 : {"errors":[{"msg":"'ps' value (10000) must be less than 500"}]}
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:55)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:50)
	at org.sonarqube.ws.client.component.ComponentsService.search(ComponentsService.java:58)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjects(SonarServer.java:146)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjectsAndModules(SonarServer.java:118)
	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:574)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

The problem here is that the page size is set to 10000 while the max allowed value is 500. this issue comes up with a fresh install of the plugin and adding a new SonarQube server and downloading the sources for the first time.

**Comment by omayevskiy** [comment]
I don't have this issue, I guess this depends on sonar server version, which one do u have?

**Comment by djas19** [comment]
i'm running SonarQube version 7.4.0.18908
with a postgres DB version 11.1

**Comment by omayevskiy** [comment]
please note that current LTS is SonarQube 6.7.x
see https://www.sonarqube.org/downloads/

**Comment by omayevskiy** [comment]
won't fix
