### ISSUE TITLE
IOException: Cannot run program ""

### ISSUE THREAD

**Issue by jwenting** [sonar-intellij-plugin/sonar-intellij-plugin#228]
Getting the following trying to analyse using version 2.6.2:

INFO 10:51:43.118 > Downloading issues for SonarQube resource xxxxxxxxxxxxxx:develop
INFO 10:51:46.046 > Downloaded 952 issues in 00:02:985
INFO 10:51:46.046 > Creating index for SonarQube resource xxxxxxxxxxxxxx:develop
INFO 10:51:46.060 > Start processing 690 files and 952 issues with 8 threads
INFO 10:51:46.249 > 67 / 690 files processed
INFO 10:51:46.320 > 134 / 690 files processed
INFO 10:51:46.484 > 335 / 690 files processed
INFO 10:51:46.745 > 670 / 690 files processed
INFO 10:51:46.768 > Finished creating index with 946 issues for SonarQube resource xxxxxxxxxxxxxx:develop in 00:00:722
INFO 10:51:46.782 > working dir: D:\dev\xxxxxxxxxxxxxxxxx
INFO 10:51:46.782 > executing: 
ERROR 10:51:46.783 > java.io.IOException: Cannot run program "" (in directory "D:\dev\xxxxxxxxxxxxxxx"): CreateProcess error=87, The parameter is incorrect
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.execute(RunLocalAnalysisScriptTask.java:136)
	at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.run(RunLocalAnalysisScriptTask.java:109)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:146)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:298)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:430)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$2(GlobalInspectionContextBase.java:260)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:260)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:215)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=87, The parameter is incorrect
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 26 more

**Comment by omayevskiy** [comment]
looks the local analysis script is missing

**Comment by DjVreditel** [comment]
> looks the local analysis script is missing in your settings

I have same problem and i have Local Analysis Script
