### ISSUE TITLE
Exception Invalid file .../cell in SonarQube Community Plugin v2.6.4

### ISSUE THREAD

**Issue by rasenderhase** [sonar-intellij-plugin/sonar-intellij-plugin#238]
I am facing this Exception in the IntelliJ IDE Fatal Errors:

    java.lang.Throwable: Invalid file: file://C:/Users/z00084or/.IntelliJIdea2018.3/config/consoles/.datagrid/cell
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:362)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:156)
	at org.intellij.sonar.DocumentChangeListener.updateHighlightingFor(DocumentChangeListener.java:74)
	at org.intellij.sonar.DocumentChangeListener.lambda$updateIssuesPositions$0(DocumentChangeListener.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

The opened project is not linked to sonar:

![image](https://user-images.githubusercontent.com/2706704/54751623-d251ad80-4bdb-11e9-9234-6f81090deacf.png)

    IntelliJ IDEA 2018.3.5 (Ultimate Edition)
    Build #IU-183.5912.21, built on February 26, 2019
    Licensed to ...
    Subscription is active until ...
    JRE: 1.8.0_152-release-1343-b28 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Windows 10 10.0

**Comment by sjovicic** [comment]
Similar  issue in v2.6.5
[sonar_qube_plugin_error.txt](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/files/3201863/sonar_qube_plugin_error.txt)
