### ISSUE TITLE
Http error 400

### ISSUE THREAD

**Issue by maxzhang666** [sonar-intellij-plugin/sonar-intellij-plugin#273]
sonarqube version : 8.6 Community
IDEA :2020.1
plugin: SonarQube Community Plugin 2.9

When i sync the issue,i got this

```
INFO 10:30:11.250 > Downloading issues for SonarQube resource eya-micro-service

ERROR 10:30:11.347 > Error 400 on http://**/api/issues/search?componentRoots=eya-micro-service&ps=-1&projectKeys=eya-micro-service&resolved=false : {"errors":[{"msg":"Page size must be between 1 and 500 (got -1)"}]}

INFO 10:30:11.347 > Downloaded 0 issues in 00:00:097
```

It seems that the value of the parameter ps is illegal

**Comment by maxzhang666** [comment]
and I manually access this link and can get the issue normally when ps uses 1

**Comment by omayevskiy** [comment]
you are using version 2.9

but: 2.9.2 fix error invalid page size issue #268

upgrade plugin version should fix the issue

**Comment by maxzhang666** [comment]
> you are using version 2.9
> 
> but: 2.9.2 fix error invalid page size issue #268
> 
> upgrade plugin version should fix the issue
> the latest version at the time of writing is 2.9.6

but i'm using IDEA for 2019.3
and i can't using the last version IDEA

**Comment by omayevskiy** [comment]
> sonarqube version : 8.6 Community
> IDEA :2020.1
> plugin: SonarQube Community Plugin 2.9

SonarQube Community Plugin 2.9 is not compatible with IDEA 2019.3

**Comment by maxzhang666** [comment]
Emma... Is this means i can't use your pkugin?

**Comment by omayevskiy** [comment]
you could:
- check out the version before 2.9.0
- apply https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/issues/268
- install your fix locally
- (optionally) share your version with the community

**Comment by maxzhang666** [comment]
I tried ，i got some errors，would you please tell the version 2. 9. 0's tag or commit hash what is?

**Comment by omayevskiy** [comment]
latest 2.8.4 commit hash:
https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/commit/9d723a61ea6f8430e6864d5bc93aaf615a98ee14

**Comment by omayevskiy** [comment]
2.9.0 commit hash (compatible with 2020.1):
https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/commit/61dca5f7a201e554ed83dd6dbd5cf6e9ea9fc26e

**Comment by maxzhang666** [comment]
Tk u

**Comment by maxzhang666** [comment]
> latest 2.8.4 commit hash (compatible with 2019.3):
> [9d723a6](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/commit/9d723a61ea6f8430e6864d5bc93aaf615a98ee14)

I checkout with version 9d723a6 and build it
when click button "download resource",i got error like this
and i don't know how to fix it
would you help me?
```
java.lang.NoClassDefFoundError: org/sonarqube/ws/client/WsConnector
	at org.intellij.sonar.sonarserver.SonarServer.<init>(SonarServer.java:42)
	at org.intellij.sonar.sonarserver.SonarServer.create(SonarServer.java:50)
	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.sonarqube.ws.client.WsConnector PluginClassLoader[org.mayevskiy.intellij.sonar, 2.8.4] com.intellij.ide.plugins.cl.PluginClassLoader@7f6c8b48
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 20 more
```
