### ISSUE TITLE
Crash with PyCharm 2021.1.1

### ISSUE THREAD

**Issue by andrewvaughanj** [sonar-intellij-plugin/sonar-intellij-plugin#281]
We're currently using the following versions:

- `sonar-intellij-plugin` @ 2.9.9
- PyCharm @ 2021.1.1
- `sonar-scanner` @ 4.6.0-2311
- SonarQube @ 8.5.1

When we (myself and @SZVector) analyse from within PyCharm, we get the following:

```
java.io.FileNotFoundException:  (No such file or directory)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:125)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:115)
    at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:420)
    at com.google.common.io.CharSource.read(CharSource.java:147)
    at com.google.common.io.Files.toString(Files.java:264)
    at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.readIssuesFromSonarReport(RunLocalAnalysisScriptTask.java:251)
    at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.logAnalysisResultToConsole(RunLocalAnalysisScriptTask.java:240)
    at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.execute(RunLocalAnalysisScriptTask.java:189)
    at org.intellij.sonar.analysis.RunLocalAnalysisScriptTask.run(RunLocalAnalysisScriptTask.java:149)
    at org.intellij.sonar.analysis.SonarQubeInspectionContext$InspectionToolsProcessor.runScriptTaskFrom(SonarQubeInspectionContext.java:300)
    at org.intellij.sonar.analysis.SonarQubeInspectionContext$InspectionToolsProcessor.runLocalAnalysisScriptForNewIssues(SonarQubeInspectionContext.java:289)
    at org.intellij.sonar.analysis.SonarQubeInspectionContext$InspectionToolsProcessor.runInspectionTools(SonarQubeInspectionContext.java:123)
    at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:90)
    at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:303)
    at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:273)
    at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$4(GlobalInspectionContextBase.java:261)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:261)
    at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:214)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

However, `sonar-scanner` has completed successfully, and we **do** see the updated code on the SonarQube side (so sonar-scanner has definitely worked!), it just seems that the reporting afterwards falls apart inside of PyCharm. 

This looks like it could be a regression of #267 -- however, is this an "us" problem or a `sonar-intellij-plugin` problem? If the latter, is there any further details we can provide here?

**Comment by omayevskiy** [comment]
Check if local analysis is enabled and deactivate it.

**Comment by SimonYZhou** [comment]
@omayevskiy 
I had the same issue now,
According this linke, sonar-report.json is not available any more.
https://community.sonarsource.com/t/sonar-report-json-is-this-file-still-available/5827/3
