### ISSUE TITLE
IntelliJ reports an error after sonar code analysis, when bound to a sonarcloud.io server.

### ISSUE THREAD

**Issue by S0UGATA** [sonar-intellij-plugin/sonar-intellij-plugin#283]
Stacktrace: 
```
java.lang.ClassCastException: class org.intellij.sonar.persistence.IssuesByFileIndexProjectService cannot be cast to class org.intellij.sonar.persistence.IssuesByFileIndexProjectService (org.intellij.sonar.persistence.IssuesByFileIndexProjectService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @66b39397; org.intellij.sonar.persistence.IssuesByFileIndexProjectService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4dedee4)
	at org.intellij.sonar.persistence.IssuesByFileIndexProjectService.getInstance(IssuesByFileIndexProjectService.java:33)
	at org.intellij.sonar.index.IssuesByFileIndex.getIndex(IssuesByFileIndex.java:17)
	at org.intellij.sonar.index.IssuesByFileIndex.getIssuesForFile(IssuesByFileIndex.java:30)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.putIssuesToInvisibleHighlightersFor(SonarExternalAnnotator.java:98)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.createSonarIssues(SonarExternalAnnotator.java:85)
	at org.intellij.sonar.analysis.SonarExternalAnnotator.lambda$doAnnotate$0(SonarExternalAnnotator.java:72)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by dc185334** [comment]
The similar for Webstorm 2021.1.3:
```WebStorm 2021.1.3
Build #WS-211.7628.25, built on June 30, 2021
Licensed to XXX / XXXXXXX
Subscription is active until XXXX XX, 202X.
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Non-Bundled Plugins: zielu.gittoolbox (203.5.10), org.mayevskiy.intellij.sonar (2.9.9), org.sonarlint.idea (5.1.0.34721)
```

Stacktrace:
```java.lang.Throwable: Light files should have PSI only in one project, existing=com.intellij.psi.SingleRootFileViewProvider{vFile=LightVirtualFile: /Dummy.txt, content=VirtualFileContent{size=0}, eventSystemEnabled=true} in Project(name=ccm-office-bff, containerState=COMPONENT_CREATED, componentStore=/Users/DC185334/Desktop/ncr-swt-retail/ccm-office-bff), requested in Project(name=ccm-office, containerState=COMPONENT_CREATED, componentStore=/Users/DC185334/Desktop/ncr-swt-retail/ccm-office)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.checkHasNoOtherPsi(FileManagerImpl.java:205)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:194)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:356)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:154)
	at org.intellij.sonar.DocumentChangeListener.updateHighlightingFor(DocumentChangeListener.java:152)
	at org.intellij.sonar.DocumentChangeListener.lambda$updateIssuesPositions$3(DocumentChangeListener.java:82)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.intellij.sonar.DocumentChangeListener.lambda$updateIssuesPositions$4(DocumentChangeListener.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
